name: mtggen
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip==23.3.2
  - unidecode==1.3.7
  - numpy==1.26.2
  - pytorch==2.1.2
  - pytorch-cuda==12.1
  - pip:
    - tensorflow[and-cuda]==2.15.0.post1
    - tqdm==4.66.1
    - diffusers==0.24.0
    - transformers==4.36.2
    - accelerate==0.25.0
    - compel==2.0.2
